export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS'
export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS'
export const SUCCESS_GET_LOGDDETAIL = 'SUCCESS_GET_LOGDDETAIL'
export const FAILURE_GET_LOGDDETAIL = 'FAILURE_GET_LOGDDETAIL'
export const SUCCESS_GET_DIRECTORYLIST = 'SUCCESS_GET_DIRECTORYLIST'
export const FAILURE_GET_DIRECTORYLIST = 'FAILURE_GET_DIRECTORYLIST'
export const SUCCESS_GET_CHANNELLIST = 'SUCCESS_GET_CHANNELLIST'
export const SUCCESS_GET_OPERATIONLIST = 'SUCCESS_GET_OPERATIONLIST'
export const FAILURE_GET_OPERATIONLIST = 'FAILURE_GET_OPERATIONLIST'
export const SUCCESS_GET_AUDITORLIST = 'SUCCESS_GET_AUDITORLIST'
export const FAILURE_GET_AUDITORLIST = 'FAILURE_GET_AUDITORLIST'
export const GET_HAS_PRIVILEGE = 'GET_HAS_PRIVILEGE'



